# Generated by Django 4.1.6 on 2023-03-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user_list',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
