# Generated by Django 4.1.6 on 2023-03-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_room_user_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_list',
        ),
    ]
