# Generated by Django 4.1.6 on 2023-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_roomusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomusers',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roomusers',
            name='username',
        ),
        migrations.AddField(
            model_name='roomusers',
            name='username_room',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
